### ISSUE TITLE
手势释放之后没有动画效果

### ISSUE THREAD

**Issue by KIDXO** [zzyspace/ZYDraggableView#2]
手势释放之后view回到原frame时没有动画效果，就是瞬间回到原位置。

**Comment by zzyspace** [comment]
Demo也不行吗

**Comment by KIDXO** [comment]
是的，Demo也是一样，iPhone 6 Plus & iOS 10

**Comment by zzyspace** [comment]
收到, 应该是iOS10的适配问题

**Comment by KIDXO** [comment]
应该是，iOS8.2测试没问题

**Comment by zzyspace** [comment]
已修复: [#7c8adcc](https://github.com/zzyspace/ZYDraggableView/commit/7c8adccdb72c8ba6e1ca0b6e5d6d73ca0412eaa0)
原因: iOS 10 下, remove 掉 UIAttachmentBehavior 之后, view 不再停留在 UIAttachmentBehavior 的 anchorPoint 的位置, 而是无动画地返回初始位置. 所以等于是在同一个点(初始位置)进行了 UISnapBehavior.

**Comment by KIDXO** [comment]
👍
